FROM localhost:5001/vpp-test-base:latest

# We don't need to install these packages as they're in the base image
# Just install anything specific to VPP that isn't in the base

ARG UBUNTU_VERSION
ARG TARGETARCH
ARG CODENAME
ARG GO_VERSION=1.23.10
RUN echo "I'm building for ${TARGETARCH}" \
&& wget -t 2 "https://go.dev/dl/go${GO_VERSION}.linux-${TARGETARCH}.tar.gz" -O /tmp/go.tar.gz \
&& tar -xzf /tmp/go.tar.gz -C /usr/local \
&& rm /tmp/go.tar.gz

# Install Docker CLI from official repository
RUN install -m 0755 -d /etc/apt/keyrings \
&& curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc \
&& chmod a+r /etc/apt/keyrings/docker.asc \
&& echo "deb [arch=${TARGETARCH} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu ${CODENAME} stable" > /etc/apt/sources.list.d/docker.list \
&& apt-get update \
&& apt-get install -y docker-ce-cli \
&& rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/local/go/bin/go /usr/bin/go
